if(EXISTS "/home/lampinen/Ohjelmointi/Cpp/EngineSimulator/engine-sim/build/dependencies/submodules/simple-2d-constraint-solver/simple-2d-constraint-solver-test[1]_tests.cmake")
  include("/home/lampinen/Ohjelmointi/Cpp/EngineSimulator/engine-sim/build/dependencies/submodules/simple-2d-constraint-solver/simple-2d-constraint-solver-test[1]_tests.cmake")
else()
  add_test(simple-2d-constraint-solver-test_NOT_BUILT simple-2d-constraint-solver-test_NOT_BUILT)
endif()
